# Generated by Django 2.1.7 on 2019-03-16 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarAxle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axleNo', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': '车厢车轴配置',
                'verbose_name_plural': '车厢车轴配置',
                'ordering': ['carriageNo', 'axleNo'],
            },
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('carriageNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
                ('use', models.FloatField()),
            ],
            options={
                'verbose_name': '车厢管理',
                'verbose_name_plural': '车厢管理',
                'ordering': ['carriageNo'],
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('millisec', models.IntegerField()),
                ('axle1_pressure', models.FloatField()),
                ('axle2_pressure', models.FloatField()),
                ('axle3_pressure', models.FloatField()),
                ('axle4_pressure', models.FloatField()),
                ('carAxle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='axlepress.CarAxle')),
            ],
            options={
                'verbose_name': '车轴压力',
                'verbose_name_plural': '车轴压力',
                'ordering': ['carAxle'],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField()),
                ('num3', models.FloatField()),
                ('num4', models.FloatField()),
                ('num5', models.FloatField()),
                ('num6', models.FloatField()),
                ('num7', models.FloatField()),
                ('num8', models.FloatField()),
            ],
            options={
                'verbose_name': '原始数据',
                'verbose_name_plural': '原始数据',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('trainNo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('startP', models.CharField(max_length=10)),
                ('endP', models.CharField(max_length=10)),
                ('startT', models.DateTimeField()),
                ('endT', models.DateTimeField()),
                ('use', models.FloatField()),
            ],
            options={
                'verbose_name': '车次管理',
                'verbose_name_plural': '车次管理',
                'ordering': ['startT'],
            },
        ),
        migrations.CreateModel(
            name='TrainCarriage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startT', models.DateTimeField()),
                ('carriageNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='axlepress.Carriage', verbose_name='carriage_No')),
                ('trainNo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='axlepress.Train', verbose_name='train_No')),
            ],
            options={
                'verbose_name': '车次车厢配置',
                'verbose_name_plural': '车次车厢配置',
                'ordering': ['trainNo'],
            },
        ),
        migrations.AddField(
            model_name='pressure',
            name='rawData',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='axlepress.RawData'),
        ),
        migrations.AddField(
            model_name='caraxle',
            name='carriageNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='axlepress.Carriage', verbose_name='车厢'),
        ),
    ]
