# Generated by Django 2.1.7 on 2019-03-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axlepress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriage',
            name='carriageNo',
            field=models.FloatField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
